Document: canaima-notas
Title: Debian canaima-notas Manual
Author: <insert document author here>
Abstract: This manual describes what canaima-notas is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/canaima-notas/canaima-notas.sgml.gz

Format: postscript
Files: /usr/share/doc/canaima-notas/canaima-notas.ps.gz

Format: text
Files: /usr/share/doc/canaima-notas/canaima-notas.text.gz

Format: HTML
Index: /usr/share/doc/canaima-notas/html/index.html
Files: /usr/share/doc/canaima-notas/html/*.html


